### ISSUE TITLE
Fix types

### ISSUE THREAD

**Issue by theoparis** [moncefplastin07/deno-os#1]
It seems like in the mod.ts:
```typescript
const os:any = {
    ...systemPaths,
    ...systemInfo
}
```
the :` any` part is causing my ide to not give autocompletion.
![image](https://user-images.githubusercontent.com/11761863/111402238-18855e80-8688-11eb-9b53-91bdddda85e3.png)

**Comment by theoparis** [comment]
Also, is this package still active? It hasn't been updated in 6 months...

**Comment by theoparis** [comment]
Ok, it also seems like the way you defined the exports are going to cause issues. You put `any` again in systemInfo.ts.

Two possible solutions I can think of:
1. use `{ platform: () => string, ... }` instead of `any`
2. put `export const platform =` instead of `systeminfo.platform = `

**Comment by moncefplastin07** [comment]
We thank you for your interest .. I am now going to fix the problem that you referred to .. Yes, it is still active .. If you want to contribute to its development then welcome
